version: "3.9"

services:
  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - inventory-network

  price-db:
    image: postgres:16
    container_name: price-db
    environment:
      POSTGRES_DB: pricedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - price_db_data:/var/lib/postgresql/data
    networks:
      - inventory-network

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    networks:
      - inventory-network

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - inventory-network

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - inventory-network

volumes:
  product_db_data:
  price_db_data:
  inventory_db_data:
  order_db_data:
  auth_db_data:

networks:
  inventory-network:
    driver: bridge